changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - github-actions[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Security and Governance
      labels:
        - security
        - governance
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Maintenance
      labels:
        - chore
        - dependencies
